server.port=${PORT:8081}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.globally_quoted_identifiers=true

app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-hours=24
app.jwt.cookie-name=jwt_token

app.cors.allowed-origin=${FRONTEND_URL}

spring.application.name=user-auth-backend